# .github/workflows/gh-pages.yml
# https://github.com/marketplace/actions/github-pages-custom-deploy

name: Github Pages Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      #- uses: sterlingwes/gh-pages-deploy-action@v1.1
      #  with:
      #    access-token: ${{ secrets.ACCESS_TOKEN }}
      #    source-directory: public
      #    build-command: npm run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public




